version: "3.8"

services:
  # Runs on port 5432:
  # Postgres 15 database
  ttt-db:
    container_name: ttt-db
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"

  # Runs on port 8080:
  # Development backend server
  ttt-backend:
    container_name: ttt-backend
    build:
      context: ./backend
      dockerfile: $PWD/docker/go/dev.Dockerfile
    volumes:
      - ./backend:/app
      - cache-go-mod-ttt-backend:/go
    depends_on:
      - ttt-db
    ports:
      - "8080:8080"

  # Development frontend server
  ttt-frontend:
    container_name: ttt-frontend
    build:
      context: ./frontend
      dockerfile: $PWD/docker/vite/dev.Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
      - "5173:5173"

volumes:
  cache-go-mod-ttt-backend:
