root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = [""]
  bin = "./tmp/server"
  cmd = "go build -o ./tmp/server ./main.go"
  delay = 300
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "toml"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
