// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BfiAnswer is the predicate function for bfianswer builders.
type BfiAnswer func(*sql.Selector)

// BfiQuestion is the predicate function for bfiquestion builders.
type BfiQuestion func(*sql.Selector)

// BfiReport is the predicate function for bfireport builders.
type BfiReport func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupRun is the predicate function for grouprun builders.
type GroupRun func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
