/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * TT API
 * Team tuner API documentation
 * OpenAPI spec version: 1.0
 */

export type GetStudentSortOrder =
  (typeof GetStudentSortOrder)[keyof typeof GetStudentSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetStudentSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
