/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * TT API
 * Team tuner API documentation
 * OpenAPI spec version: 1.0
 */
import type { OutPaginationOut } from './outPaginationOut';
import type { GetStudent200AllOf } from './getStudent200AllOf';

export type GetStudent200 = OutPaginationOut & GetStudent200AllOf;
