/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * TT API
 * Teeam tuner API documentation
 * OpenAPI spec version: 1.0
 */

export interface OutAnswerOut {
  answer: number;
  answer_id: string;
}
