/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * TT API
 * Team tuner API documentation
 * OpenAPI spec version: 1.0
 */
import type { OutBoxPlotItem } from './outBoxPlotItem';

export interface OutBigFiveBoxPlot {
  agreeableness: OutBoxPlotItem;
  conscientious: OutBoxPlotItem;
  extraversion: OutBoxPlotItem;
  neuroticism: OutBoxPlotItem;
  openness: OutBoxPlotItem;
}
