/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * TT API
 * Team tuner API documentation
 * OpenAPI spec version: 1.0
 */

export interface OutBoxPlotItem {
  dataPoints: number[];
  max: number;
  mean: number;
  min: number;
  q1: number;
  q3: number;
}
