/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * TT API
 * Team tuner API documentation
 * OpenAPI spec version: 1.0
 */
import type { OutDailyStat } from './outDailyStat';

export interface OutDailyActivity {
  activity: OutDailyStat[];
  endTime: string;
  startTime: string;
}
