/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * TT API
 * Team tuner API documentation
 * OpenAPI spec version: 1.0
 */

export type OutOutUserRole =
  (typeof OutOutUserRole)[keyof typeof OutOutUserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OutOutUserRole = {
  student: 'student',
  admin: 'admin',
} as const;
