/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * TT API
 * Team tuner API documentation
 * OpenAPI spec version: 1.0
 */

export interface OutPaginationOut {
  content: unknown;
  currentPage: number;
  limit: number;
  offset: number;
  totalCount: number;
  totalPages: number;
}
