/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * TT API
 * Team tuner API documentation
 * OpenAPI spec version: 1.0
 */
import type { OutOutUserRole } from './outOutUserRole';

export interface OutWhoAmIOut {
  finished_bfi: boolean;
  github_username: string;
  id: string;
  role: OutOutUserRole;
}
