/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * TT API
 * Teeam tuner API documentation
 * OpenAPI spec version: 1.0
 */

export type PostGroupCourseIdFormParams = {
  /**
 * Required
Array length must be at least 4
Each element must be greater than 0 and less than 10
 */
  groupSizes: number[];
};
