import { ReactComponent as Illustration } from '@/assets/illustration.svg';
import { Anchor, Box, Button, Flex, Text, Title } from '@mantine/core';
import { IconBrandGithub } from '@tabler/icons-react';
import { usePostLoginGithub } from '../api/login/login';

const LoginPage = () => {
  const { mutateAsync } = usePostLoginGithub();

  // on click redirects to the github login page
  // the url is generated by the backend so it inserts things like the client id etc.
  const onClick = async () => {
    const data = await mutateAsync({
      data: {
        // set the redirect url to the current url + /logged-in
        navigateTo: window.location.href + 'logged-in',
      },
    });

    window.location.replace(data.redirectUrl);
  };

  return (
    <Flex w="100%" h="100vh" direction="row" align="center" justify="center">
      <Flex mx="30px">
        <Flex
          align="start"
          direction="column"
          w="350px"
          gap="lg"
          justify="center"
        >
          <Title size="50px" fw="700">
            Welcome
          </Title>
          <Text>
            to{' '}
            <Text c="grape" fw="900" span>
              Team Tuner
            </Text>
          </Text>
          <Text c="dimmed">
            To proceed, please login using GitHub. If you do not have an account
            yet, visit{' '}
            <Anchor href={'https://github.com/'}> www.github.com </Anchor>{' '}
            first.
          </Text>
          <Button
            onClick={onClick}
            leftIcon={<IconBrandGithub size="1rem" />}
            sx={(theme) => ({
              backgroundColor:
                theme.colors.dark[theme.colorScheme === 'dark' ? 9 : 6],
              color: '#fff',
              '&:hover': {
                backgroundColor:
                  theme.colors.dark[theme.colorScheme === 'dark' ? 9 : 6],
              },
            })}
          >
            {' '}
            Login with github{' '}
          </Button>
        </Flex>
        <Box>
          <Illustration width="100%" height="800px" />
        </Box>
      </Flex>
    </Flex>
  );
};

export default LoginPage;
