// Code generated by ent, DO NOT EDIT.

package model

import (
	"context"
	"jv/team-tone-tuner/model/grouprun"
	"jv/team-tone-tuner/model/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GroupRunDelete is the builder for deleting a GroupRun entity.
type GroupRunDelete struct {
	config
	hooks    []Hook
	mutation *GroupRunMutation
}

// Where appends a list predicates to the GroupRunDelete builder.
func (grd *GroupRunDelete) Where(ps ...predicate.GroupRun) *GroupRunDelete {
	grd.mutation.Where(ps...)
	return grd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (grd *GroupRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, grd.sqlExec, grd.mutation, grd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (grd *GroupRunDelete) ExecX(ctx context.Context) int {
	n, err := grd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (grd *GroupRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(grouprun.Table, sqlgraph.NewFieldSpec(grouprun.FieldID, field.TypeUUID))
	if ps := grd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, grd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	grd.mutation.done = true
	return affected, err
}

// GroupRunDeleteOne is the builder for deleting a single GroupRun entity.
type GroupRunDeleteOne struct {
	grd *GroupRunDelete
}

// Where appends a list predicates to the GroupRunDelete builder.
func (grdo *GroupRunDeleteOne) Where(ps ...predicate.GroupRun) *GroupRunDeleteOne {
	grdo.grd.mutation.Where(ps...)
	return grdo
}

// Exec executes the deletion query.
func (grdo *GroupRunDeleteOne) Exec(ctx context.Context) error {
	n, err := grdo.grd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{grouprun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (grdo *GroupRunDeleteOne) ExecX(ctx context.Context) {
	if err := grdo.Exec(ctx); err != nil {
		panic(err)
	}
}
